site_name: ODEpower Documentation
repo_url: https://github.com/yourusername/ODEpower
nav:
  - Home: index.md
  - API Reference:
      - ODEpower: api/ODEpower.md
      - ODEgraph: api/ODEgraph.md
      - ODEtool: api/ODEtool.md
      - ODEsimulation: api/ODEsimulation.md
      - ODEplot: api/ODEplot.md
      - ODEmatlab: api/ODEmatlab.md
  - Getting Started: getting_started.md
  - Examples:
      - Create Grid (Symbolic): example_create_grid.md
      - Simulate Grid (Numerical): example_simulate_grid.md
      - Simulink Co-Simulation: example_simulink.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ODEpower]
