name: Upload Package to PyPI

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ODEpower
    permissions:
      id-token: write
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install build dependencies
      working-directory: ./ODEpower
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel build
    - name: Build package
      working-directory: ./ODEpower
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./ODEpower/dist
